# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Graphite
    orgId: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  - name: Postgres
    type: postgres
    uid: d7b6774ba1c1420aafd3b7ddfc9064c8
    url: postgres:5432
    database: app
    user: postgres
    editable: true
    isDefault: true
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: true